### ISSUE TITLE
Setup with new DB doesn't work

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#190] opened 2016-03-11 15:52 UTC
```
edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ResourceIntegrationTest > classMethod FAILED
    org.jooq.exception.DataAccessException: SQL [insert into `crowdcontrol`.`Platform` (`id_platform`, `name`, `render_calibrations`, `needs_email`) values (?, ?, ?, ?)]; Field 'inactive' doesn't have a default value
        at org.jooq.impl.Utils.translate(Utils.java:1690)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
        at org.jooq.impl.DefaultDSLContext.executeInsert(DefaultDSLContext.java:2761)
        at edu.kit.ipd.crowdcontrol.objectservice.database.operations.PlatformOperations.createPlatform(PlatformOperations.java:64)
        at edu.kit.ipd.crowdcontrol.objectservice.crowdworking.PlatformManager.lambda$new$0(PlatformManager.java:69)
        at java.util.HashMap.forEach(HashMap.java:1280)
        at edu.kit.ipd.crowdcontrol.objectservice.crowdworking.PlatformManager.<init>(PlatformManager.java:60)
        at edu.kit.ipd.crowdcontrol.objectservice.Main.boot(Main.java:113)
        at edu.kit.ipd.crowdcontrol.objectservice.Main.main(Main.java:84)
        at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ResourceIntegrationTest.setUp(ResourceIntegrationTest.java:29)

        Caused by:
        java.sql.SQLException: Field 'inactive' doesn't have a default value
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
            at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
            at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
            at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
            at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
            at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
            at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
            at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
            at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
            at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
            at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
            at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:410)
            at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:284)
            at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
            ... 8 more
```

**Comment by kelunik** [comment] 2016-03-11 15:54
Configuration:

``` yml
database:
  url: jdbc:mysql://localhost:3306/crowdcontrol
  dialect: MYSQL
  writing:
    user: crowdcontrol
    password: ***
  readonly:
    user: crowdcontrol
    password: ***

deployment:
  origin: http://localhost:3000

platforms :
  - type: dummy

mail:
  disabled: true

moneytransfer:
  payOffThreshold: 0
  parsingPassword: test
  notificationMailAddress: pseipd@gmail.com
  scheduleInterval: 7

log:
  com.zaxxer.hikari: WARN
  org.eclipse.jetty: WARN
  org.jooq.impl.DefaultBinding: WARN
  org.jooq.impl.DefaultConnectionProvider: WARN
  org.jooq.tools.StopWatch: WARN
  spark.webserver.MatcherFilter: WARN
  spark.Request: WARN
```

**Comment by LeanderK** [comment] 2016-03-11 16:10
with new db? the field inactive was added 24 days ago

**Comment by LeanderK** [comment] 2016-03-11 16:13
and the platform-manager uses storePlatform, not createPlatoform. I think maybe your code is outdated and your DB up to date?

**Comment by marcelhollerbach** [comment] 2016-03-11 16:15
Also the PlatformManager sets the flag in the record ... so the field is set.

**Comment by LeanderK** [comment] 2016-03-11 16:23
closing because can't reproduce!

**Closed as completed by LeanderK** 2016-03-11 16:23 UTC
Labels: bug

**Comment by marcelhollerbach** [comment] 2016-03-11 16:27
reminds me to 
http://41.media.tumblr.com/tumblr_m0xp5k8EM01rrju89o1_500.jpg

**Comment by kelunik** [comment] 2016-03-11 16:47
Works after `gradle clean` …
